import 'country_phone_data.dart';

class Autogenerated {
  Autogenerated({List<CountryPhoneData> countryPhoneDataList}) {
    _countryPhoneDataList = countryPhoneDataList;
  }

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['countryPhoneDataList'] != null) {
      _countryPhoneDataList = List<CountryPhoneData>();
      json['countryPhoneDataList'].forEach((v) {
        _countryPhoneDataList.add(CountryPhoneData.fromJson(v));
      });
    }
  }

  List<CountryPhoneData> _countryPhoneDataList;

  List<CountryPhoneData> get countryPhoneDataList => _countryPhoneDataList;

  set countryPhoneDataList(List<CountryPhoneData> countryPhoneDataList) =>
      _countryPhoneDataList = countryPhoneDataList;

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (_countryPhoneDataList != null) {
      data['countryPhoneDataList'] =
          this._countryPhoneDataList.map((v) => v.toJson()).toList();
    }
    return data;
  }
}
