import 'dart:async';
import 'package:user_mobile/temp/country_phone_data_test_2.dart';

import '../models/country_phone_data.dart';
import 'api/phone_api.dart';

class PhoneRepository {
  final PhoneApi phoneApi = PhoneApi();

  Future<List<CountryPhoneData>> getCountriesPhoneData() async {
    final List<CountryPhoneData> list = <CountryPhoneData>[];
    final dynamic data = await phoneApi.requestCountriesPhoneData();
    for (Map<String, dynamic> country in data) {
      list.add(CountryPhoneData.fromJson(country));
    }
    return list;
  }

  Future<List<CountryPhoneData>> getTopCountriesPhoneData() async {
    final dynamic data = await phoneApi.requestCountriesPhoneData();
    return Autogenerated.fromJson(data).topCountryPhonesData;
  }

  Future<int> getCreationDate() async {
    final dynamic data = await phoneApi.requestCountriesPhoneData();
    return Autogenerated.fromJson(data).creationDate;
  }

  Future<String> getCountryByIp() async {
    return await phoneApi.countryLookUp();
  }
}
