import 'dart:async';
import '../../temp/models/country_phone_data_test_2.dart';
import '../models/country_phone_data.dart';
import 'api/phone_api.dart';

class PhoneRepository {
  final PhoneApi phoneApi = PhoneApi();

  Future<List<CountryPhoneData>> getCountriesPhoneData() async {
    final dynamic data = await phoneApi.requestCountriesPhoneData();
    final List<CountryPhoneData> list =
        Autogenerated.fromJson(data).topCountryPhonesData;
    list.addAll(Autogenerated.fromJson(data).countryPhonesData);
    return list;
  }

  Future<int> getCreationDate() async {
    final dynamic data = await phoneApi.requestCountriesPhoneData();
    return Autogenerated.fromJson(data).creationDate;
  }

  Future<String> getCountryByIp() async {
    return await phoneApi.countryLookUp();
  }
}
