import 'dart:async';
import 'dart:convert';
import 'package:flutter/services.dart' show rootBundle;
import '../src/models/country_phone_data.dart';
import 'package:user_mobile/temp/country_phone_data_test_2.dart';
import '../src/resources/phone_repository.dart';


class TestPhoneRepository extends PhoneRepository {
 /* @override
  Future<List<CountryPhoneData>> getCountriesPhoneData() async {
    final String response = await rootBundle.loadString('lib/assets/data.json');
    final List<CountryPhoneData> list =
        Autogenerated.fromJson(json.decode(response)).countryPhoneDataList;
    return list;
  }*/

  @override
  Future<List<CountryPhoneData>> getCountriesPhoneData() async {
    final String response = await rootBundle.loadString('lib/assets/country_phone_data.json');
    final List<CountryPhoneData> list =
        Autogenerated.fromJson(json.decode(response)).countryPhonesData;
    return list;
  }
}
