import 'dart:async';
import 'dart:convert';
import 'package:flutter/services.dart' show rootBundle;
import '../src/models/country_phone_data.dart';
import '../src/resources/phone_repository.dart';
import '../temp/country_phone_data_test.dart';



class TestPhoneRepository extends PhoneRepository {
  @override
  Future<List<CountryPhoneData>> getCountriesPhoneData() async {
    final String response = await rootBundle.loadString('lib/assets/data.json');
    final List<CountryPhoneData> list =
        Autogenerated.fromJson(json.decode(response)).countryPhoneDataList;
    return list;
  }
}
