import 'dart:async';
import 'dart:convert';
import 'package:flutter/services.dart' show rootBundle;
import '../../src/models/country_phone_data.dart';
import '../../src/resources/phone_repository.dart';
import '../models/country_phone_data_test_2.dart';

class TestPhoneRepository extends PhoneRepository {

  final String uRl = 'lib/assets/country_phone_data.json';

  @override
  Future<List<CountryPhoneData>> getCountriesPhoneData() async {
    final String response = await rootBundle.loadString(uRl);
    final List<CountryPhoneData> list =
        Autogenerated.fromJson(json.decode(response)).topCountryPhonesData;
    list.addAll(
        Autogenerated.fromJson(json.decode(response)).countryPhonesData);
    return list;
  }

  @override
  Future<int> getCreationDate() async {
    final String response = await rootBundle.loadString(uRl);
    return Autogenerated.fromJson(json.decode(response)).creationDate;
  }
}
